package com.moonbolt.cityscale;

public class Player {
	
	public Player() {}
	
	//Player Character
	public String AccountID;
	
	public String Name_1;
	public String Sex_1;
	public int Level_1;
	public String Map_1;
	public int Exp_1;
	public String Job_1;
	public int Hp_1;
	public int Mp_1;
	public int Money_1;
	public int HpMax_1;
	public int MpMax_1;
	public int regenTime_1;
	public int regenTimeMax_1;
	public float PosX_1;
	public float PosY_1;
	public String Walk_1;
	public int Frame_1;
	public String Target_1;
	public int AtkTimer_1;
	public int AtkTimerMax_1;
	public String Casting_1;
	public int Atk_1;
	public int Def_1;
	public int Evasion_1;
	public String Side_1;
	public String SetUpper_1;
	public String SetBottom_1;
	public String Hair_1;
	public String Color_1;
	public String Hat_1;
	public String Weapon_1;
	public String Crystal1_1;
	public String Crystal2_1;
	public String Crystal3_1;
	public String Crystal4_1;
	public String Crystal5_1;
	public int StatusPoint_1;
	public int Str_1;
	public int Agi_1;
	public int Vit_1;
	public int Dex_1;
	public int Wis_1;
	public int Stamina_1;
	public int StaminaMax_1;
	public int StaminaTimer_1;
	public String Itens_1;
	public String Quests_1;
	public String hotkey1_1;
	public String hotkey2_1;
	public String buffA_1;
	public int BuffTimeA_1;
	public String buffB_1;
	public int BuffTimeB_1;
	public String buffC_1;
	public int BuffTimeC_1;
	public String party_1;
	public String playerInBattle_1;
	public String playerInAttack_1;
	public String playerInCast_1;
	
	public String hungry_1;
	public String bath_1;
	public String sleep_1;
	public String fun_1;
	public String health_1;
	public String social_1;
	public String cousine_1;
	public String mechanic_1;
	public String charisma_1;
	public String physic_1;
	public String talent_1;
	public String mental_1;
	public String socialjob_1;
	public String sociallevel_1;
	public String socialmoney_1;
	
	public String Name_2;
	public String Sex_2;
	public int Level_2;
	public String Map_2;
	public int Exp_2;
	public String Job_2;
	public int Hp_2;
	public int Mp_2;
	public int Money_2;
	public int HpMax_2;
	public int MpMax_2;
	public int regenTime_2;
	public int regenTimeMax_2;
	public float PosX_2;
	public float PosY_2;
	public String Walk_2;
	public int Frame_2;
	public String Target_2;
	public int AtkTimer_2;
	public int AtkTimerMax_2;
	public String Casting_2;
	public int Atk_2;
	public int Def_2;
	public int Evasion_2;
	public String Side_2;
	public String SetUpper_2;
	public String SetBottom_2;
	public String Hair_2;
	public String Color_2;
	public String Hat_2;
	public String Weapon_2;
	public String Crystal1_2;
	public String Crystal2_2;
	public String Crystal3_2;
	public String Crystal4_2;
	public String Crystal5_2;
	public int StatusPoint_2;
	public int Str_2;
	public int Agi_2;
	public int Vit_2;
	public int Dex_2;
	public int Wis_2;
	public int Stamina_2;
	public int StaminaMax_2;
	public int StaminaTimer_2;
	public String Itens_2;
	public String Quests_2;
	public String hotkey1_2;
	public String hotkey2_2;
	public String buffA_2;
	public int BuffTimeA_2;
	public String buffB_2;
	public int BuffTimeB_2;
	public String buffC_2;
	public int BuffTimeC_2;
	public String party_2;
	public String playerInBattle_2;
	public String playerInAttack_2;
	public String playerInCast_2;
	
	public String hungry_2;
	public String bath_2;
	public String sleep_2;
	public String fun_2;
	public String health_2;
	public String social_2;
	public String cousine_2;
	public String mechanic_2;
	public String charisma_2;
	public String physic_2;
	public String talent_2;
	public String mental_2;
	public String socialjob_2;
	public String sociallevel_2;
	public String socialmoney_2;
	
	public String Name_3;
	public String Sex_3;
	public int Level_3;
	public String Map_3;
	public int Exp_3;
	public String Job_3;
	public int Hp_3;
	public int Mp_3;
	public int Money_3;
	public int HpMax_3;
	public int MpMax_3;
	public int regenTime_3;
	public int regenTimeMax_3;
	public float PosX_3;
	public float PosY_3;
	public String Walk_3;
	public int Frame_3;
	public String Target_3;
	public int AtkTimer_3;
	public int AtkTimerMax_3;
	public String Casting_3;
	public int Atk_3;
	public int Def_3;
	public int Evasion_3;
	public String Side_3;
	public String SetUpper_3;
	public String SetBottom_3;
	public String Hair_3;
	public String Color_3;
	public String Hat_3;
	public String Weapon_3;
	public String Crystal1_3;
	public String Crystal2_3;
	public String Crystal3_3;
	public String Crystal4_3;
	public String Crystal5_3;
	public int StatusPoint_3;
	public int Str_3;
	public int Agi_3;
	public int Vit_3;
	public int Dex_3;
	public int Wis_3;
	public int Stamina_3;
	public int StaminaMax_3;
	public int StaminaTimer_3;
	public String Itens_3;
	public String Quests_3;
	public String hotkey1_3;
	public String hotkey2_3;
	public String buffA_3;
	public int BuffTimeA_3;
	public String buffB_3;
	public int BuffTimeB_3;
	public String buffC_3;
	public int BuffTimeC_3;
	public String party_3;
	public String playerInBattle_3;
	public String playerInAttack_3;
	public String playerInCast_3;
	
	public String hungry_3;
	public String bath_3;
	public String sleep_3;
	public String fun_3;
	public String health_3;
	public String social_3;
	public String cousine_3;
	public String mechanic_3;
	public String charisma_3;
	public String physic_3;
	public String talent_3;
	public String mental_3;
	public String socialjob_3;
	public String sociallevel_3;
	public String socialmoney_3;
	
	public String Name_A;
	public String Sex_A;
	public int Level_A;
	public String Map_A;
	public int Exp_A;
	public String Job_A;
	public int Hp_A;
	public int Mp_A;
	public int Money_A;
	public int HpMax_A;
	public int MpMax_A;
	public int regenTime_A;
	public int regenTimeMax_A;
	public float PosX_A;
	public float PosY_A;
	public String Walk_A;
	public int Frame_A;
	public String Target_A;
	public int AtkTimer_A;
	public int AtkTimerMax_A;
	public String Casting_A;
	public int Atk_A;
	public int Def_A;
	public int Evasion_A;
	public String Side_A;
	public String SetUpper_A;
	public String SetBottom_A;
	public String Hair_A;
	public String Color_A;
	public String Hat_A;
	public String Weapon_A;
	public String Crystal1_A;
	public String Crystal2_A;
	public String Crystal3_A;
	public String Crystal4_A;
	public String Crystal5_A;
	public int StatusPoint_A;
	public int Str_A;
	public int Agi_A;
	public int Vit_A;
	public int Dex_A;
	public int Wis_A;
	public int Stamina_A;
	public int StaminaMax_A;
	public int StaminaTimer_A;
	public String Itens_A;
	public String Quests_A;
	public String hotkey1_A;
	public String hotkey2_A;
	public String buffA_A;
	public int BuffTimeA_A;
	public String buffB_A;
	public int BuffTimeB_A;
	public String buffC_A;
	public int BuffTimeC_A;
	public String party_A;
	public String playerInBattle_A;
	public String playerInAttack_A;
	public String playerInCast_A;
	
	public String hungry_A;
	public String bath_A;
	public String sleep_A;
	public String fun_A;
	public String health_A;
	public String social_A;
	public String cousine_A;
	public String mechanic_A;
	public String charisma_A;
	public String physic_A;
	public String talent_A;
	public String mental_A;
	public String socialjob_A;
	public String sociallevel_A;
	public String socialmoney_A;
	
	
	public String pet;
	public String pethungry;
	public String petcare;
	public String petTraining;
	public String petBath;
	public String petLevel;
		
		
	public void CreateNewChar(String name, String sex, String hair, String color, int slot) {
		if(slot == 1) {
			Name_1 = name;
			Sex_1 = sex;
			Level_1 = 1;
			Exp_1 = 0;
			Job_1 = "Aprendiz";
			Map_1 = "MetroStation";
			Hp_1 = 100;
			Mp_1 = 100;
			HpMax_1 = 100;
			MpMax_1 = 100;
			regenTime_1 = 6000;
			regenTimeMax_1 = 6000;
			PosX_1 = -0.5f;
			PosY_1 = -4;
			Walk_1 = "no";
			Frame_1 = 1;
			Money_1 = 0;
			AtkTimer_1 = 200;
			AtkTimerMax_1 = 200;
			Casting_1 = "no";
			Target_1 = "none";
			Atk_1 = 9;
			Def_1 = 1;
			Evasion_1 = 1;
			Side_1 = "front";
			SetUpper_1 = "basic";
			SetBottom_1 = "basic";
			Hair_1 = hair;
			Color_1 = color;
			Hat_1 = "none";
			Weapon_1 = "basicknife";
			Crystal1_1 = "none";
			Crystal2_1 = "none";
			Crystal3_1 = "none";
			Crystal4_1 = "none";
			Crystal5_1 = "none";
			StatusPoint_1 = 0;
			Str_1 = 1;
			Agi_1 = 1;
			Vit_1 = 1;
			Dex_1 = 1;
			Wis_1 = 1;
			Stamina_1 = 100;
			StaminaMax_1 = 100;
			StaminaTimer_1 = 1200;
			buffA_1 = "none";
			buffB_1 = "none";
			buffC_1 = "none";
			BuffTimeA_1 = 0;
			BuffTimeB_1 = 0;
			BuffTimeC_1 = 0;
			party_1 = "none";
			playerInBattle_1 = "no";
			playerInAttack_1 = "no";
			playerInCast_1 = "no";
			hotkey1_1 = "none";
			hotkey2_1 = "none";
			hungry_1 = "100";
			bath_1 = "100";
			sleep_1 = "100";
			fun_1 = "100";
			health_1= "1";
			social_1= "1";
			cousine_1= "1";
			mechanic_1= "1";
			charisma_1= "1";
			physic_1= "1";
			talent_1= "1";
			mental_1= "1";
			socialjob_1= "none";
			sociallevel_1= "1";
			socialmoney_1= "1";
				
	        String itensList = "";
	        for(int i = 0; i < 16; i++) {
	            if(i == 0) { itensList = itensList + "[hpcan#30]-"; } 
	            if(i == 1) {  if(sex.equals("M")) {itensList = itensList + "[basicset_m#1]-"; } else { itensList = itensList + "[basicset_f#1]-"; }}
	            if(i == 2) {  itensList = itensList + "[basicknife#1]-"; } 
	            if(i > 2) { itensList = itensList + "[NONE]-"; }          
	        }
	        Itens_1 = itensList;
		}
		
		if(slot == 2) {
			Name_2 = name;
			Sex_2 = sex;
			Level_2 = 1;
			Exp_2 = 0;
			Job_2 = "Aprendiz";
			Map_2 = "MetroStation";
			Hp_2 = 100;
			Mp_2 = 100;
			HpMax_2 = 100;
			MpMax_2 = 100;
			regenTime_2 = 6000;
			regenTimeMax_2 = 6000;
			PosX_2 = -0.5f;
			PosY_2 = -4;
			Walk_2 = "no";
			Frame_2 = 1;
			Money_2 = 0;
			AtkTimer_2 = 200;
			AtkTimerMax_2 = 200;
			Casting_2 = "no";
			Target_2 = "none";
			Atk_2 = 9;
			Def_2 = 1;
			Evasion_2 = 1;
			Side_2 = "front";
			SetUpper_2 = "basic";
			SetBottom_2 = "basic";
			Hair_2 = hair;
			Color_2 = color;
			Hat_2 = "none";
			Weapon_2 = "basicknife";
			Crystal1_2 = "none";
			Crystal2_2 = "none";
			Crystal3_2 = "none";
			Crystal4_2 = "none";
			Crystal5_2 = "none";
			StatusPoint_2 = 0;
			Str_2 = 1;
			Agi_2 = 1;
			Vit_2 = 1;
			Dex_2 = 1;
			Wis_2 = 1;
			Stamina_2 = 100;
			StaminaMax_2 = 100;
			StaminaTimer_2 = 1200;
			buffA_2 = "none";
			buffB_2 = "none";
			buffC_2 = "none";
			BuffTimeA_2 = 0;
			BuffTimeB_2 = 0;
			BuffTimeC_2 = 0;
			party_2 = "none";
			playerInBattle_2 = "no";
			playerInAttack_2 = "no";
			playerInCast_2 = "no";
			hotkey1_2 = "none";
			hotkey2_2 = "none";
			hungry_2 = "100";
			bath_2 = "100";
			sleep_2 = "100";
			fun_2 = "100";
			health_2= "1";
			social_2= "1";
			cousine_2= "1";
			mechanic_2= "1";
			charisma_2= "1";
			physic_2= "1";
			talent_2= "1";
			mental_2= "1";
			socialjob_2= "none";
			sociallevel_2= "1";
			socialmoney_2= "1";
				
	        String itensList = "";
	        for(int i = 0; i < 16; i++) {
	            if(i == 0) { itensList = itensList + "[hpcan#30]-"; } 
	            if(i == 1) {  if(sex.equals("M")) {itensList = itensList + "[basicset_m#1]-"; } else { itensList = itensList + "[basicset_f#1]-"; }}
	            if(i == 2) {  itensList = itensList + "[basicknife#1]-"; } 
	            if(i > 2) { itensList = itensList + "[NONE]-"; }          
	        }
	        Itens_2 = itensList;
		}
		
		if(slot == 3) {
			Name_3 = name;
			Sex_3 = sex;
			Level_3 = 1;
			Exp_3 = 0;
			Job_3 = "Aprendiz";
			Map_3 = "MetroStation";
			Hp_3 = 100;
			Mp_3 = 100;
			HpMax_3 = 100;
			MpMax_3 = 100;
			regenTime_3 = 6000;
			regenTimeMax_3 = 6000;
			PosX_3 = -0.5f;
			PosY_3 = -4;
			Walk_3 = "no";
			Frame_3 = 1;
			Money_3 = 0;
			AtkTimer_3 = 200;
			AtkTimerMax_3 = 200;
			Casting_3 = "no";
			Target_3 = "none";
			Atk_3 = 9;
			Def_3 = 1;
			Evasion_3 = 1;
			Side_3 = "front";
			SetUpper_3 = "basic";
			SetBottom_3 = "basic";
			Hair_3 = hair;
			Color_3 = color;
			Hat_3 = "none";
			Weapon_3 = "basicknife";
			Crystal1_3 = "none";
			Crystal2_3 = "none";
			Crystal3_3 = "none";
			Crystal4_3 = "none";
			Crystal5_3 = "none";
			StatusPoint_3 = 0;
			Str_3 = 1;
			Agi_3 = 1;
			Vit_3 = 1;
			Dex_3 = 1;
			Wis_3 = 1;
			Stamina_3 = 100;
			StaminaMax_3 = 100;
			StaminaTimer_3 = 1200;
			buffA_3 = "none";
			buffB_3 = "none";
			buffC_3 = "none";
			BuffTimeA_3 = 0;
			BuffTimeB_3 = 0;
			BuffTimeC_3 = 0;
			party_3 = "none";
			playerInBattle_3 = "no";
			playerInAttack_3 = "no";
			playerInCast_3 = "no";
			hotkey1_3 = "none";
			hotkey2_3 = "none";
			hungry_3 = "100";
			bath_3 = "100";
			sleep_3 = "100";
			fun_3 = "100";
			health_3= "1";
			social_3= "1";
			cousine_3= "1";
			mechanic_3= "1";
			charisma_3= "1";
			physic_3= "1";
			talent_3= "1";
			mental_3= "1";
			socialjob_3= "none";
			sociallevel_3= "1";
			socialmoney_3= "1";
				
	        String itensList = "";
	        for(int i = 0; i < 16; i++) {
	            if(i == 0) { itensList = itensList + "[hpcan#30]-"; } 
	            if(i == 1) {  if(sex.equals("M")) {itensList = itensList + "[basicset_m#1]-"; } else { itensList = itensList + "[basicset_f#1]-"; }}
	            if(i == 2) {  itensList = itensList + "[basicknife#1]-"; } 
	            if(i > 2) { itensList = itensList + "[NONE]-"; }          
	        }
	        Itens_3 = itensList;
		}
	}
	
	public void SetActiveChar(int num) {
		if(num == 1) {
			Name_A = Name_1;
			Sex_A = Sex_1;
			Level_A = Level_1;
			Exp_A = Exp_1;
			Job_A = Job_1;
			Map_A = Map_1;
			Hp_A = Hp_1;
			Mp_A = Mp_1;
			HpMax_A = HpMax_1;
			MpMax_A = MpMax_1;
			regenTime_A = regenTime_1;
			regenTimeMax_A = regenTimeMax_1;
			PosX_A = PosX_1;
			PosY_A = PosY_1;
			Walk_A = Walk_1;
			Frame_A = Frame_1;
			Money_A = Money_1;
			AtkTimer_A = AtkTimer_1;
			AtkTimerMax_A = AtkTimerMax_1;
			Casting_A = Casting_1;
			Target_A = Target_1;
			Atk_A = Atk_1;
			Def_A = Def_1;
			Evasion_A = Evasion_1;
			Side_A = Side_1;
			SetUpper_A = SetUpper_1;
			SetBottom_A = SetBottom_1;
			Hair_A = Hair_1;
			Color_A = Color_1;
			Hat_A = Hat_1;
			Weapon_A = Weapon_1;
			Crystal1_A = Crystal1_1;
			Crystal2_A = Crystal2_1;
			Crystal3_A = Crystal3_1;
			Crystal4_A = Crystal4_1;
			Crystal5_A = Crystal5_1;
			StatusPoint_A = StatusPoint_1;
			Str_A = Str_1;
			Agi_A = Agi_1;
			Vit_A = Vit_1;
			Dex_A = Dex_1;
			Wis_A = Wis_1;
			Stamina_A = Stamina_1;
			StaminaMax_A = StaminaMax_1;
			StaminaTimer_A = StaminaTimer_1;
			buffA_A = buffA_1;
			buffB_A = buffB_1;
			buffC_A = buffC_1;
			BuffTimeA_A = BuffTimeA_1;
			BuffTimeB_A = BuffTimeB_1;
			BuffTimeC_A = BuffTimeC_1;
			party_A = party_1;
			playerInBattle_A = playerInBattle_1;
			playerInAttack_A = playerInAttack_1;
			playerInCast_A = playerInCast_1;
			hotkey1_A = hotkey1_1;
			hotkey2_A = hotkey2_1;
			hungry_A = hungry_1;
			bath_A = bath_1;
			sleep_A = sleep_1;
			fun_A = fun_1;
			health_A = health_1;
			social_A = social_1;
			cousine_A = cousine_1;
			mechanic_A = mechanic_1;
			charisma_A = charisma_1;
			physic_A = physic_1;
			talent_A = talent_1;
			mental_A = mental_1;
			socialjob_A = socialjob_1;
			sociallevel_A = sociallevel_1;
			socialmoney_A = socialmoney_1;
		}
		
		if(num == 2) {
			Name_A = Name_2;
			Sex_A = Sex_2;
			Level_A = Level_2;
			Exp_A = Exp_2;
			Job_A = Job_2;
			Map_A = Map_2;
			Hp_A = Hp_2;
			Mp_A = Mp_2;
			HpMax_A = HpMax_2;
			MpMax_A = MpMax_2;
			regenTime_A = regenTime_2;
			regenTimeMax_A = regenTimeMax_2;
			PosX_A = PosX_2;
			PosY_A = PosY_2;
			Walk_A = Walk_2;
			Frame_A = Frame_2;
			Money_A = Money_2;
			AtkTimer_A = AtkTimer_2;
			AtkTimerMax_A = AtkTimerMax_2;
			Casting_A = Casting_2;
			Target_A = Target_2;
			Atk_A = Atk_2;
			Def_A = Def_2;
			Evasion_A = Evasion_2;
			Side_A = Side_2;
			SetUpper_A = SetUpper_2;
			SetBottom_A = SetBottom_2;
			Hair_A = Hair_2;
			Color_A = Color_2;
			Hat_A = Hat_2;
			Weapon_A = Weapon_2;
			Crystal1_A = Crystal1_2;
			Crystal2_A = Crystal2_2;
			Crystal3_A = Crystal3_2;
			Crystal4_A = Crystal4_2;
			Crystal5_A = Crystal5_2;
			StatusPoint_A = StatusPoint_2;
			Str_A = Str_2;
			Agi_A = Agi_2;
			Vit_A = Vit_2;
			Dex_A = Dex_2;
			Wis_A = Wis_2;
			Stamina_A = Stamina_2;
			StaminaMax_A = StaminaMax_2;
			StaminaTimer_A = StaminaTimer_2;
			buffA_A = buffA_2;
			buffB_A = buffB_2;
			buffC_A = buffC_2;
			BuffTimeA_A = BuffTimeA_2;
			BuffTimeB_A = BuffTimeB_2;
			BuffTimeC_A = BuffTimeC_2;
			party_A = party_2;
			playerInBattle_A = playerInBattle_2;
			playerInAttack_A = playerInAttack_2;
			playerInCast_A = playerInCast_2;
			hotkey1_A = hotkey1_2;
			hotkey2_A = hotkey2_2;
			hungry_A = hungry_2;
			bath_A = bath_2;
			sleep_A = sleep_2;
			fun_A = fun_2;
			health_A = health_2;
			social_A = social_2;
			cousine_A = cousine_2;
			mechanic_A = mechanic_2;
			charisma_A = charisma_2;
			physic_A = physic_2;
			talent_A = talent_2;
			mental_A = mental_2;
			socialjob_A = socialjob_2;
			sociallevel_A = sociallevel_2;
			socialmoney_A = socialmoney_2;
		}
		
		if(num == 3) {
			Name_A = Name_3;
			Sex_A = Sex_3;
			Level_A = Level_3;
			Exp_A = Exp_3;
			Job_A = Job_3;
			Map_A = Map_3;
			Hp_A = Hp_3;
			Mp_A = Mp_3;
			HpMax_A = HpMax_3;
			MpMax_A = MpMax_3;
			regenTime_A = regenTime_3;
			regenTimeMax_A = regenTimeMax_3;
			PosX_A = PosX_3;
			PosY_A = PosY_3;
			Walk_A = Walk_3;
			Frame_A = Frame_3;
			Money_A = Money_3;
			AtkTimer_A = AtkTimer_3;
			AtkTimerMax_A = AtkTimerMax_3;
			Casting_A = Casting_3;
			Target_A = Target_3;
			Atk_A = Atk_3;
			Def_A = Def_3;
			Evasion_A = Evasion_3;
			Side_A = Side_3;
			SetUpper_A = SetUpper_3;
			SetBottom_A = SetBottom_3;
			Hair_A = Hair_3;
			Color_A = Color_3;
			Hat_A = Hat_3;
			Weapon_A = Weapon_3;
			Crystal1_A = Crystal1_3;
			Crystal2_A = Crystal2_3;
			Crystal3_A = Crystal3_3;
			Crystal4_A = Crystal4_3;
			Crystal5_A = Crystal5_3;
			StatusPoint_A = StatusPoint_3;
			Str_A = Str_3;
			Agi_A = Agi_3;
			Vit_A = Vit_3;
			Dex_A = Dex_3;
			Wis_A = Wis_3;
			Stamina_A = Stamina_3;
			StaminaMax_A = StaminaMax_3;
			StaminaTimer_A = StaminaTimer_3;
			buffA_A = buffA_3;
			buffB_A = buffB_3;
			buffC_A = buffC_3;
			BuffTimeA_A = BuffTimeA_3;
			BuffTimeB_A = BuffTimeB_3;
			BuffTimeC_A = BuffTimeC_3;
			party_A = party_3;
			playerInBattle_A = playerInBattle_3;
			playerInAttack_A = playerInAttack_3;
			playerInCast_A = playerInCast_3;
			hotkey1_A = hotkey1_3;
			hotkey2_A = hotkey2_3;
			hungry_A = hungry_3;
			bath_A = bath_3;
			sleep_A = sleep_3;
			fun_A = fun_3;
			health_A = health_3;
			social_A = social_3;
			cousine_A = cousine_3;
			mechanic_A = mechanic_3;
			charisma_A = charisma_3;
			physic_A = physic_3;
			talent_A = talent_3;
			mental_A = mental_3;
			socialjob_A = socialjob_3;
			sociallevel_A = sociallevel_3;
			socialmoney_A = socialmoney_3;
		}
	}
}
