package com.moonbolt.cityscale.models;

import java.util.ArrayList;

public class Monster {
		//Monster
		public String MobName;
		public int MobHp;
		public int MobMp;
		public int MobHpMax;
		public int MobMpMax;
		public int MobFrame;
		public float MobPosX;
		public float MobPosY;
		public int MobExp;
		public String MobID;
		public int MobMoney;
		public int MobSizeY;
		public int MobSizeX;
		public String MobTarget;
		public String MobDead;
		public int MobTimeDead;
		public String MobSkillChance;
		public int MobAtk;
		public int MobEvade;
		public String MobPosition;
		public int MobRandomSt;
		public int MobTimerMov;
		public int MobFrameTime;
		public int MobAtkTimer;
		public int MobAtkTimerMax;
		public int MobLevel;
		public String MobMap;
		public float MobPosXFinal;
		public float MobPosYFinal;
		public boolean GotFinal;
		public String Status;


		public ArrayList<Monster> LoadMonsterDataSewers(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "poyo";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 220;
			MobA.MobMp = 220;
			MobA.MobHpMax = 220;
			MobA.MobMpMax = 220;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 5;
			MobA.MobID = "PoyoA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 30;
			MobA.MobSizeX = 22;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 2;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 1;
			MobA.MobMap = "Sewers";
			MobA.MobPosXFinal = 0;
			MobA.MobPosYFinal = 0;
			MobA.GotFinal = false;
			MobA.Status = "none";

			Monster MobB = new Monster();
			MobB.MobName = "poyo";
			MobB.MobHp = 220;
			MobB.MobMp = 220;
			MobB.MobHpMax = 220;
			MobB.MobMpMax = 220;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 5;
			MobB.MobID = "PoyoB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 30;
			MobB.MobSizeX = 22;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 2;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 1;
			MobB.MobMap = "Sewers";
			MobB.MobPosXFinal = 0;
			MobB.MobPosYFinal = 0;
			MobB.GotFinal = false;
			MobB.Status = "none";

			Monster MobC = new Monster();
			MobC.MobName = "aranarc";
			MobC.MobHp = 370;
			MobC.MobMp = 370;
			MobC.MobHpMax = 370;
			MobC.MobMpMax = 370;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 20;
			MobC.MobID = "AranarcA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 25;
			MobC.MobSizeX = 22;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 4;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 1;
			MobC.MobMap = "Sewers";
			MobC.MobPosXFinal = 0;
			MobC.MobPosYFinal = 0;
			MobC.GotFinal = false;
			MobC.Status = "none";

			Monster MobD = new Monster();
			MobD.MobName = "rat";
			MobD.MobHp = 560;
			MobD.MobMp = 560;
			MobD.MobHpMax = 560;
			MobD.MobMpMax = 560;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 60;
			MobD.MobID = "RatA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 20;
			MobD.MobSizeX = 20;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 15;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 1;
			MobD.MobMap = "Sewers";
			MobD.MobPosXFinal = 0;
			MobD.MobPosYFinal = 0;
			MobD.GotFinal = false;
			MobD.Status = "none";

			Monster MobE = new Monster();
			MobE.MobName = "snake";
			MobE.MobHp = 1200;
			MobE.MobMp = 1200;
			MobE.MobHpMax = 1200;
			MobE.MobMpMax = 1200;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 200;
			MobE.MobID = "SnakeA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 34;
			MobE.MobSizeX = 30;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 22;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 1;
			MobE.MobMap = "Sewers";
			MobE.MobPosXFinal = 0;
			MobE.MobPosYFinal = 0;
			MobE.GotFinal = false;
			MobE.Status = "none";


			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);
			
			return listMonsters;

		}
		
		public ArrayList<Monster> LoadMonsterDataForest(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "slime";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 220;
			MobA.MobMp = 220;
			MobA.MobHpMax = 220;
			MobA.MobMpMax = 220;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 5;
			MobA.MobID = "SlimeA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 20;
			MobA.MobSizeX = 14;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 2;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 1;
			MobA.MobMap = "Forest";
			MobA.MobPosXFinal = 0;
			MobA.MobPosYFinal = 0;
			MobA.GotFinal = false;
			MobA.Status = "none";


			Monster MobB = new Monster();
			MobB.MobName = "slime";
			MobB.MobHp = 220;
			MobB.MobMp = 220;
			MobB.MobHpMax = 220;
			MobB.MobMpMax = 220;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 5;
			MobB.MobID = "SlimeB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 20;
			MobB.MobSizeX = 14;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 2;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 1;
			MobB.MobMap = "Forest";
			MobB.MobPosXFinal = 0;
			MobB.MobPosYFinal = 0;
			MobB.GotFinal = false;
			MobB.Status = "none";

			Monster MobC = new Monster();
			MobC.MobName = "bee";
			MobC.MobHp = 370;
			MobC.MobMp = 370;
			MobC.MobHpMax = 370;
			MobC.MobMpMax = 370;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 20;
			MobC.MobID = "BeeA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 22;
			MobC.MobSizeX = 16;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 4;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 1;
			MobC.MobMap = "Forest";
			MobC.MobPosXFinal = 0;
			MobC.MobPosYFinal = 0;
			MobC.GotFinal = false;
			MobC.Status = "none";

			Monster MobD = new Monster();
			MobD.MobName = "goblin";
			MobD.MobHp = 560;
			MobD.MobMp = 560;
			MobD.MobHpMax = 560;
			MobD.MobMpMax = 560;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 60;
			MobD.MobID = "GoblinA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 22;
			MobD.MobSizeX = 15;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 15;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 1;
			MobD.MobMap = "Forest";
			MobD.MobPosXFinal = 0;
			MobD.MobPosYFinal = 0;
			MobD.GotFinal = false;
			MobD.Status = "none";

			Monster MobE = new Monster();
			MobE.MobName = "enty";
			MobE.MobHp = 1200;
			MobE.MobMp = 1200;
			MobE.MobHpMax = 120;
			MobE.MobMpMax = 120;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 200;
			MobE.MobID = "EntyA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 40;
			MobE.MobSizeX = 28;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 22;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 1;
			MobE.MobMap = "Forest";
			MobE.MobPosXFinal = 0;
			MobE.MobPosYFinal = 0;
			MobE.GotFinal = false;
			MobE.Status = "none";

			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);

			return listMonsters;
		}
		
		public ArrayList<Monster> LoadMonsterDataWatercave(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "fisko";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 2200;
			MobA.MobMp = 2200;
			MobA.MobHpMax = 2200;
			MobA.MobMpMax = 2200;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 220;
			MobA.MobID = "FiskoA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 20;
			MobA.MobSizeX = 14;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 50;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 2;
			MobA.MobMap = "Watercave";
			MobA.MobPosXFinal = 0;
			MobA.MobPosYFinal = 0;
			MobA.GotFinal = false;
			MobA.Status = "none";


			Monster MobB = new Monster();
			MobB.MobName = "fisko";
			MobB.MobHp = 2200;
			MobB.MobMp = 2200;
			MobB.MobHpMax = 2200;
			MobB.MobMpMax = 2200;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 220;
			MobB.MobID = "FiskoB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 20;
			MobB.MobSizeX = 14;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 50;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 2;
			MobB.MobMap = "Watercave";
			MobB.MobPosXFinal = 0;
			MobB.MobPosYFinal = 0;
			MobB.GotFinal = false;
			MobB.Status = "none";

			Monster MobC = new Monster();
			MobC.MobName = "shelly";
			MobC.MobHp = 2800;
			MobC.MobMp = 2800;
			MobC.MobHpMax = 2800;
			MobC.MobMpMax = 2800;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 260;
			MobC.MobID = "ShellyA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 22;
			MobC.MobSizeX = 16;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 75;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 2;
			MobC.MobMap = "Watercave";
			MobC.MobPosXFinal = 0;
			MobC.MobPosYFinal = 0;
			MobC.GotFinal = false;
			MobC.Status = "none";

			Monster MobD = new Monster();
			MobD.MobName = "marit";
			MobD.MobHp = 3400;
			MobD.MobMp = 3400;
			MobD.MobHpMax = 3400;
			MobD.MobMpMax = 3400;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 340;
			MobD.MobID = "MaritA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 32;
			MobD.MobSizeX = 20;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 88;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 2;
			MobD.MobMap = "Watercave";
			MobD.MobPosXFinal = 0;
			MobD.MobPosYFinal = 0;
			MobD.GotFinal = false;
			MobD.Status = "none";

			Monster MobE = new Monster();
			MobE.MobName = "tencle";
			MobE.MobHp = 5300;
			MobE.MobMp = 5300;
			MobE.MobHpMax = 5300;
			MobE.MobMpMax = 5300;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 450;
			MobE.MobID = "TencleA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 40;
			MobE.MobSizeX = 28;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 100;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 2;
			MobE.MobMap = "Watercave";
			MobE.MobPosXFinal = 0;
			MobE.MobPosYFinal = 0;
			MobE.GotFinal = false;
			MobE.Status = "none";

			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);

			return listMonsters;
		}
		
		public ArrayList<Monster> LoadMonsterDataDesert(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "cactus";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 2200;
			MobA.MobMp = 2200;
			MobA.MobHpMax = 2200;
			MobA.MobMpMax = 2200;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 220;
			MobA.MobID = "CactusA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 20;
			MobA.MobSizeX = 14;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 50;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 2;
			MobA.MobMap = "Desert";
			MobA.MobPosXFinal = 0;
			MobA.MobPosYFinal = 0;
			MobA.GotFinal = false;
			MobA.Status = "none";


			Monster MobB = new Monster();
			MobB.MobName = "cactus";
			MobB.MobHp = 2200;
			MobB.MobMp = 2200;
			MobB.MobHpMax = 2200;
			MobB.MobMpMax = 2200;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 220;
			MobB.MobID = "CactusB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 20;
			MobB.MobSizeX = 14;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 50;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 2;
			MobB.MobMap = "Desert";
			MobB.MobPosXFinal = 0;
			MobB.MobPosYFinal = 0;
			MobB.GotFinal = false;
			MobB.Status = "none";

			Monster MobC = new Monster();
			MobC.MobName = "harpia";
			MobC.MobHp = 2800;
			MobC.MobMp = 2800;
			MobC.MobHpMax = 2800;
			MobC.MobMpMax = 2800;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 260;
			MobC.MobID = "HarpiaA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 28;
			MobC.MobSizeX = 20;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 75;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 2;
			MobC.MobMap = "Desert";
			MobC.MobPosXFinal = 0;
			MobC.MobPosYFinal = 0;
			MobC.GotFinal = false;
			MobC.Status = "none";

			Monster MobD = new Monster();
			MobD.MobName = "golem";
			MobD.MobHp = 3400;
			MobD.MobMp = 3400;
			MobD.MobHpMax = 3400;
			MobD.MobMpMax = 3400;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 340;
			MobD.MobID = "GolemA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 50;
			MobD.MobSizeX = 30;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 88;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 2;
			MobD.MobMap = "Desert";
			MobD.MobPosXFinal = 0;
			MobD.MobPosYFinal = 0;
			MobD.GotFinal = false;
			MobD.Status = "none";

			Monster MobE = new Monster();
			MobE.MobName = "brimworn";
			MobE.MobHp = 5300;
			MobE.MobMp = 5300;
			MobE.MobHpMax = 5300;
			MobE.MobMpMax = 5300;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 450;
			MobE.MobID = "BrimwornA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 40;
			MobE.MobSizeX = 28;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 100;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 2;
			MobE.MobMap = "Desert";
			MobE.MobPosXFinal = 0;
			MobE.MobPosYFinal = 0;
			MobE.GotFinal = false;
			MobE.Status = "none";

			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);

			return listMonsters;
		}
		
		public ArrayList<Monster> LoadMonsterDataMines(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "ghost";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 6000;
			MobA.MobMp = 6000;
			MobA.MobHpMax = 6000;
			MobA.MobMpMax = 6000;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 650;
			MobA.MobID = "GhostA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 20;
			MobA.MobSizeX = 14;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 180;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 3;
			MobA.MobMap = "Mines";
			MobA.MobPosXFinal = 0;
			MobA.MobPosYFinal = 0;
			MobA.GotFinal = false;
			MobA.Status = "none";


			Monster MobB = new Monster();
			MobB.MobName = "ghost";
			MobB.MobHp = 6000;
			MobB.MobMp = 6000;
			MobB.MobHpMax = 6000;
			MobB.MobMpMax = 6000;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 650;
			MobB.MobID = "GhostB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 20;
			MobB.MobSizeX = 14;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 180;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 3;
			MobB.MobMap = "Mines";
			MobB.MobPosXFinal = 0;
			MobB.MobPosYFinal = 0;
			MobB.GotFinal = false;
			MobB.Status = "none";

			Monster MobC = new Monster();
			MobC.MobName = "tipper";
			MobC.MobHp = 6900;
			MobC.MobMp = 6900;
			MobC.MobHpMax = 6900;
			MobC.MobMpMax = 6900;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 880;
			MobC.MobID = "TipperA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 22;
			MobC.MobSizeX = 16;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 220;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 3;
			MobC.MobMap = "Mines";
			MobC.MobPosXFinal = 0;
			MobC.MobPosYFinal = 0;
			MobC.GotFinal = false;
			MobC.Status = "none";

			Monster MobD = new Monster();
			MobD.MobName = "urso";
			MobD.MobHp = 8500;
			MobD.MobMp = 8500;
			MobD.MobHpMax = 8500;
			MobD.MobMpMax = 8500;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 950;
			MobD.MobID = "BearA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 40;
			MobD.MobSizeX = 22;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 260;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 3;
			MobD.MobMap = "Mines";
			MobD.MobPosXFinal = 0;
			MobD.MobPosYFinal = 0;
			MobD.GotFinal = false;
			MobD.Status = "none";

			Monster MobE = new Monster();
			MobE.MobName = "caveira";
			MobE.MobHp = 12200;
			MobE.MobMp = 12200;
			MobE.MobHpMax = 12200;
			MobE.MobMpMax = 12200;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 1200;
			MobE.MobID = "DeathSkullA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 40;
			MobE.MobSizeX = 28;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 300;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 3;
			MobE.MobMap = "Mines";
			MobE.MobPosXFinal = 0;
			MobE.MobPosYFinal = 0;
			MobE.GotFinal = false;
			MobE.Status = "none";

			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);

			return listMonsters;
		}
		
		public ArrayList<Monster> LoadMonsterDataVulcano(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "flare";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 6000;
			MobA.MobMp = 6000;
			MobA.MobHpMax = 6000;
			MobA.MobMpMax = 6000;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 650;
			MobA.MobID = "FlareA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 20;
			MobA.MobSizeX = 14;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 180;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 3;
			MobA.MobMap = "Vulcano";
			MobA.MobPosXFinal = 0;
			MobA.MobPosYFinal = 0;
			MobA.GotFinal = false;
			MobA.Status = "none";


			Monster MobB = new Monster();
			MobB.MobName = "flare";
			MobB.MobHp = 6000;
			MobB.MobMp = 6000;
			MobB.MobHpMax = 6000;
			MobB.MobMpMax = 6000;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 650;
			MobB.MobID = "FlareB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 20;
			MobB.MobSizeX = 14;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 180;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 3;
			MobB.MobMap = "Vulcano";
			MobB.MobPosXFinal = 0;
			MobB.MobPosYFinal = 0;
			MobB.GotFinal = false;
			MobB.Status = "none";

			Monster MobC = new Monster();
			MobC.MobName = "salamander";
			MobC.MobHp = 6900;
			MobC.MobMp = 6900;
			MobC.MobHpMax = 6900;
			MobC.MobMpMax = 6900;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 880;
			MobC.MobID = "SalamanderA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 22;
			MobC.MobSizeX = 16;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 220;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 3;
			MobC.MobMap = "Vulcano";
			MobC.MobPosXFinal = 0;
			MobC.MobPosYFinal = 0;
			MobC.GotFinal = false;
			MobC.Status = "none";

			Monster MobD = new Monster();
			MobD.MobName = "cerberus";
			MobD.MobHp = 8500;
			MobD.MobMp = 8500;
			MobD.MobHpMax = 8500;
			MobD.MobMpMax = 8500;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 950;
			MobD.MobID = "CerberusA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 40;
			MobD.MobSizeX = 30;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 260;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 3;
			MobD.MobMap = "Vulcano";
			MobD.MobPosXFinal = 0;
			MobD.MobPosYFinal = 0;
			MobD.GotFinal = false;
			MobD.Status = "none";

			Monster MobE = new Monster();
			MobE.MobName = "hammertooth";
			MobE.MobHp = 12200;
			MobE.MobMp = 12200;
			MobE.MobHpMax = 12200;
			MobE.MobMpMax = 12200;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 1200;
			MobE.MobID = "HammertoothA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 50;
			MobE.MobSizeX = 30;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 300;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 3;
			MobE.MobMap = "Vulcano";
			MobE.MobPosXFinal = 0;
			MobE.MobPosYFinal = 0;
			MobE.GotFinal = false;
			MobE.Status = "none";

			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);

			return listMonsters;
		}
		
		public ArrayList<Monster> LoadMonsterDataSnowpalace(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "goblin";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 16200;
			MobA.MobMp = 16200;
			MobA.MobHpMax = 16200;
			MobA.MobMpMax = 16200;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 3500;
			MobA.MobID = "GoblinA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 20;
			MobA.MobSizeX = 14;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 430;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 4;
			MobA.MobMap = "Snowpalace";
			MobA.MobPosXFinal = 0;
			MobA.MobPosYFinal = 0;
			MobA.GotFinal = false;
			MobA.Status = "none";


			Monster MobB = new Monster();
			MobB.MobName = "goblin";
			MobB.MobHp = 16200;
			MobB.MobMp = 16200;
			MobB.MobHpMax = 16200;
			MobB.MobMpMax = 16200;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 3500;
			MobB.MobID = "GoblinB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 20;
			MobB.MobSizeX = 14;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 430;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 4;
			MobB.MobMap = "Snowpalace";
			MobB.MobPosXFinal = 0;
			MobB.MobPosYFinal = 0;
			MobB.GotFinal = false;
			MobB.Status = "none";

			Monster MobC = new Monster();
			MobC.MobName = "pinguim";
			MobC.MobHp = 24200;
			MobC.MobMp = 24200;
			MobC.MobHpMax = 24200;
			MobC.MobMpMax = 24200;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 4300;
			MobC.MobID = "PinguimA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 22;
			MobC.MobSizeX = 16;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 560;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 4;
			MobC.MobMap = "Snowpalace";
			MobC.MobPosXFinal = 0;
			MobC.MobPosYFinal = 0;
			MobC.GotFinal = false;
			MobC.Status = "none";

			Monster MobD = new Monster();
			MobD.MobName = "snowman";
			MobD.MobHp = 29200;
			MobD.MobMp = 29200;
			MobD.MobHpMax = 29200;
			MobD.MobMpMax = 29200;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 5600;
			MobD.MobID = "SnowmanA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 40;
			MobD.MobSizeX = 20;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 630;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 4;
			MobD.MobMap = "Snowpalace";
			MobD.MobPosXFinal = 0;
			MobD.MobPosYFinal = 0;
			MobD.GotFinal = false;
			MobD.Status = "none";

			Monster MobE = new Monster();
			MobE.MobName = "yeti";
			MobE.MobHp = 35200;
			MobE.MobMp = 35200;
			MobE.MobHpMax = 35200;
			MobE.MobMpMax = 35200;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 7800;
			MobE.MobID = "YetiA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 60;
			MobE.MobSizeX = 30;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 750;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 4;
			MobE.MobMap = "Snowpalace";
			MobE.MobPosXFinal = 0;
			MobE.MobPosYFinal = 0;
			MobE.GotFinal = false;
			MobE.Status = "none";

			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);

			return listMonsters;
		}
		
		public ArrayList<Monster> LoadMonsterDataSwamp(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "eyeball";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 16200;
			MobA.MobMp = 16200;
			MobA.MobHpMax = 16200;
			MobA.MobMpMax = 16200;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 3500;
			MobA.MobID = "EyeballA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 23;
			MobA.MobSizeX = 16;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 430;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 4;
			MobA.MobMap = "Swamp";
			MobA.MobPosXFinal = 0;
			MobA.MobPosYFinal = 0;
			MobA.GotFinal = false;
			MobA.Status = "none";


			Monster MobB = new Monster();
			MobB.MobName = "eyeball";
			MobB.MobHp = 16200;
			MobB.MobMp = 16200;
			MobB.MobHpMax = 16200;
			MobB.MobMpMax = 16200;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 3500;
			MobB.MobID = "EyeballB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 20;
			MobB.MobSizeX = 14;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 430;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 4;
			MobB.MobMap = "Swamp";
			MobB.MobPosXFinal = 0;
			MobB.MobPosYFinal = 0;
			MobB.GotFinal = false;
			MobB.Status = "none";

			Monster MobC = new Monster();
			MobC.MobName = "onulu";
			MobC.MobHp = 24200;
			MobC.MobMp = 24200;
			MobC.MobHpMax = 24200;
			MobC.MobMpMax = 24200;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 4300;
			MobC.MobID = "OnuluA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 40;
			MobC.MobSizeX = 25;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 560;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 4;
			MobC.MobMap = "Swamp";
			MobC.MobPosXFinal = 0;
			MobC.MobPosYFinal = 0;
			MobC.GotFinal = false;
			MobC.Status = "none";

			Monster MobD = new Monster();
			MobD.MobName = "cockatrix";
			MobD.MobHp = 29200;
			MobD.MobMp = 29200;
			MobD.MobHpMax = 29200;
			MobD.MobMpMax = 29200;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 5600;
			MobD.MobID = "CockatrixA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 40;
			MobD.MobSizeX = 20;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 630;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 4;
			MobD.MobMap = "Swamp";
			MobD.MobPosXFinal = 0;
			MobD.MobPosYFinal = 0;
			MobD.GotFinal = false;
			MobD.Status = "none";

			Monster MobE = new Monster();
			MobE.MobName = "mantis";
			MobE.MobHp = 35200;
			MobE.MobMp = 35200;
			MobE.MobHpMax = 35200;
			MobE.MobMpMax = 35200;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 7800;
			MobE.MobID = "MantisA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 50;
			MobE.MobSizeX = 35;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 750;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 4;
			MobE.MobMap = "Swamp";
			MobE.MobPosXFinal = 0;
			MobE.MobPosYFinal = 0;
			MobE.GotFinal = false;
			MobE.Status = "none";

			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);

			return listMonsters;
		}
}
