package com.moonbolt.cityscale.models;

import java.util.ArrayList;

public class Monster {
		//Monster
		public String MobName;
		public int MobHp;
		public int MobMp;
		public int MobHpMax;
		public int MobMpMax;
		public int MobFrame;
		public float MobPosX;
		public float MobPosY;
		public int MobExp;
		public String MobID;
		public int MobMoney;
		public int MobSizeY;
		public int MobSizeX;
		public String MobTarget;
		public String MobDead;
		public int MobTimeDead;
		public String MobSkillChance;
		public int MobAtk;
		public int MobEvade;
		public String MobPosition;
		public int MobRandomSt;
		public int MobTimerMov;
		public int MobFrameTime;
		public int MobAtkTimer;
		public int MobAtkTimerMax;
		public int MobLevel;
		public String MobMap;


		public ArrayList<Monster> LoadMonsterDataSewers(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "poyo";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 20;
			MobA.MobMp = 20;
			MobA.MobHpMax = 20;
			MobA.MobMpMax = 20;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 5;
			MobA.MobID = "PoyoA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 30;
			MobA.MobSizeX = 22;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 2;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 1;
			MobA.MobMap = "Sewers";

			Monster MobB = new Monster();
			MobB.MobName = "poyo";
			MobB.MobHp = 20;
			MobB.MobMp = 20;
			MobB.MobHpMax = 20;
			MobB.MobMpMax = 20;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 5;
			MobB.MobID = "PoyoB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 30;
			MobB.MobSizeX = 22;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 2;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 1;
			MobB.MobMap = "Sewers";

			Monster MobC = new Monster();
			MobC.MobName = "aranarc";
			MobC.MobHp = 45;
			MobC.MobMp = 45;
			MobC.MobHpMax = 45;
			MobC.MobMpMax = 45;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 10;
			MobC.MobID = "AranarcA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 25;
			MobC.MobSizeX = 22;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 4;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 4;
			MobC.MobMap = "Sewers";

			Monster MobD = new Monster();
			MobD.MobName = "rat";
			MobD.MobHp = 80;
			MobD.MobMp = 80;
			MobD.MobHpMax = 80;
			MobD.MobMpMax = 80;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 30;
			MobD.MobID = "RatA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 20;
			MobD.MobSizeX = 20;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 15;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 5;
			MobD.MobMap = "Sewers";

			Monster MobE = new Monster();
			MobE.MobName = "snake";
			MobE.MobHp = 120;
			MobE.MobMp = 120;
			MobE.MobHpMax = 120;
			MobE.MobMpMax = 120;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 60;
			MobE.MobID = "SnakeA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 34;
			MobE.MobSizeX = 30;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 22;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 8;
			MobE.MobMap = "Forest";

			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);
			
			return listMonsters;

		}
		
		public ArrayList<Monster> LoadMonsterDataForest(String map){
			
			ArrayList<Monster> listMonsters = new ArrayList<Monster>();
			
			Monster MobA = new Monster();
			
			MobA.MobName = "slime";      //MobID + MobHp + MobMp + MobPosX + MobPosY + MobTarget + MobDead
			MobA.MobHp = 20;
			MobA.MobMp = 20;
			MobA.MobHpMax = 20;
			MobA.MobMpMax = 20;
			MobA.MobFrame = 1;
			MobA.MobPosX = 20;
			MobA.MobPosY = 20;
			MobA.MobExp = 5;
			MobA.MobID = "SlimeA";
			MobA.MobMoney = 1;
			MobA.MobSizeY = 20;
			MobA.MobSizeX = 14;
			MobA.MobTarget = "none";
			MobA.MobDead = "no";
			MobA.MobTimeDead = 500;
			MobA.MobSkillChance = "";
			MobA.MobAtk = 2;
			MobA.MobEvade = 20;
			MobA.MobPosition = "left";
			MobA.MobRandomSt = 1;
			MobA.MobTimerMov = 1;
			MobA.MobFrameTime = 1;
			MobA.MobAtkTimer = 500;
			MobA.MobAtkTimerMax = 500;
			MobA.MobLevel = 1;
			MobA.MobMap = "Forest";

			Monster MobB = new Monster();
			MobB.MobName = "slime";
			MobB.MobHp = 20;
			MobB.MobMp = 20;
			MobB.MobHpMax = 20;
			MobB.MobMpMax = 20;
			MobB.MobFrame = 1;
			MobB.MobPosX = 20;
			MobB.MobPosY = 20;
			MobB.MobExp = 5;
			MobB.MobID = "SlimeB";
			MobB.MobMoney = 1;
			MobB.MobSizeY = 20;
			MobB.MobSizeX = 14;
			MobB.MobTarget = "none";
			MobB.MobDead = "no";
			MobB.MobTimeDead = 500;
			MobB.MobSkillChance = "";
			MobB.MobAtk = 2;
			MobB.MobEvade = 20;
			MobB.MobPosition = "left";
			MobB.MobRandomSt = 1;
			MobB.MobTimerMov = 1;
			MobB.MobFrameTime = 1;
			MobB.MobAtkTimer = 500;
			MobB.MobAtkTimerMax = 500;
			MobB.MobLevel = 1;
			MobB.MobMap = "Forest";

			Monster MobC = new Monster();
			MobC.MobName = "bee";
			MobC.MobHp = 45;
			MobC.MobMp = 45;
			MobC.MobHpMax = 45;
			MobC.MobMpMax = 45;
			MobC.MobFrame = 1;
			MobC.MobPosX = 112.5f;
			MobC.MobPosY = -13;
			MobC.MobExp = 10;
			MobC.MobID = "BeeA";
			MobC.MobMoney = 2;
			MobC.MobSizeY = 22;
			MobC.MobSizeX = 16;
			MobC.MobTarget = "none";
			MobC.MobDead = "no";
			MobC.MobTimeDead = 500;
			MobC.MobSkillChance = "";
			MobC.MobAtk = 4;
			MobC.MobEvade = 10;
			MobC.MobPosition = "left";
			MobC.MobRandomSt = 1;
			MobC.MobTimerMov = 1;
			MobC.MobFrameTime = 1;
			MobC.MobAtkTimer = 300;
			MobC.MobAtkTimerMax = 300;
			MobC.MobLevel = 4;
			MobC.MobMap = "Forest";

			Monster MobD = new Monster();
			MobD.MobName = "goblin";
			MobD.MobHp = 80;
			MobD.MobMp = 80;
			MobD.MobHpMax = 80;
			MobD.MobMpMax = 80;
			MobD.MobFrame = 1;
			MobD.MobPosX = 9.0f;
			MobD.MobPosY = -132;
			MobD.MobExp = 30;
			MobD.MobID = "GoblinA";
			MobD.MobMoney = 4;
			MobD.MobSizeY = 22;
			MobD.MobSizeX = 15;
			MobD.MobTarget = "none";
			MobD.MobDead = "no";
			MobD.MobTimeDead = 500;
			MobD.MobSkillChance = "";
			MobD.MobAtk = 15;
			MobD.MobEvade = 10;
			MobD.MobPosition = "left";
			MobD.MobRandomSt = 1;
			MobD.MobTimerMov = 1;
			MobD.MobFrameTime = 1;
			MobD.MobAtkTimer = 300;
			MobD.MobAtkTimerMax = 300;
			MobD.MobLevel = 5;
			MobD.MobMap = "Forest";

			Monster MobE = new Monster();
			MobE.MobName = "enty";
			MobE.MobHp = 120;
			MobE.MobMp = 120;
			MobE.MobHpMax = 120;
			MobE.MobMpMax = 120;
			MobE.MobFrame = 1;
			MobE.MobPosX = 84.5f;
			MobE.MobPosY = -129.5f;
			MobE.MobExp = 60;
			MobE.MobID = "EntyA";
			MobE.MobMoney = 5;
			MobE.MobSizeY = 40;
			MobE.MobSizeX = 28;
			MobE.MobTarget = "none";
			MobE.MobDead = "no";
			MobE.MobTimeDead = 500;
			MobE.MobSkillChance = "";
			MobE.MobAtk = 22;
			MobE.MobEvade = 10;
			MobE.MobPosition = "left";
			MobE.MobRandomSt = 1;
			MobE.MobTimerMov = 1;
			MobE.MobFrameTime = 1;
			MobE.MobAtkTimer = 400;
			MobE.MobAtkTimerMax = 400;
			MobE.MobLevel = 8;
			MobE.MobMap = "Forest";

			listMonsters.add(MobA);
			listMonsters.add(MobB);
			listMonsters.add(MobC);
			listMonsters.add(MobD);
			listMonsters.add(MobE);

			return listMonsters;
		}
}
